POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
    "username": "john_doe",
    "password": "securepassword",
    "name": "John Doe"
}

### LOGIN
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "john_doe",
    "password": "securepassword"
}


### SAY HELLO
GET http://localhost:3000/api/hello
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5fZG9lIiwiaWF0IjoxNzYyNTA3OTE4LCJleHAiOjE3NjI1OTQzMTh9.d1bAPQEN2feHhed5Jdr9HEEOghmLiJ4IKmzCbfr3Vf4
